openapi: 3.0.2
info:
  title: Heatmap API
  description: >-
    Esta api nos proporcionará las posiciones de los distintos dispositivos conectados para generar un mapa de calor.
  version: '1.0'
servers:
  - url: '/api/v1'
    description: Version1
tags:
  - name: Map
paths:
  /locations:
    get:
      tags:
        - Map
      summary: Get the locations
      operationId: getLocations
      responses:
        '200':
          $ref: '#/components/responses/200'
        '404':
          $ref: '#/components/responses/404'
components:
  schemas:
    Locations:
      type: array
      items:
        $ref: '#/components/schemas/Location'
    Location:
      type: object
      properties:
        latitude:
          type: number
          format: float
          example: 38.48492
        longitude:
          type: number
          format: float
          example: -6.2548987
        date:
          type: string
          format: date-time
          example: '2019-07-21T17:32:28Z'

  responses:
    '200':
      description: Successful response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Locations'
    '404':
      description: Not found response
      content:
        text/plain:
          schema:
            title: Endpoint not found
            type: string
            example: Not found
